### ISSUE TITLE
Phone number showing valid even if it's invalid

### ISSUE THREAD

**Issue by somanwal** [mobi/telephone_number#104]
I have installed gem in ruby on rails project, its' showing `+91 1231 231 1` as valid number but it's not a valid number. 

Example:

`TelephoneNumber.parse('+91 1231 231 1').valid? # coming true`
`TelephoneNumber.valid?('+91 1231 231 1') # coming true`
`TelephoneNumber.valid?('+91 1231 231 1', :IN) # coming true`

I have tried in demo website http://numberjack.io/ it's showing invalid to this above number.

**Comment by joshwetzel** [comment]
Hi there,

This library relies on metadata provided upstream by Google, which appears to [consider 9112312311 a valid number](http://www.libphonenumber.appspot.com/phonenumberparser?number=9112312311&country=IN). If this is not correct, you may [override the validation](https://github.com/mobi/telephone_number#override-file). Unfortunately we must rely on the metadata they provide for our official releases, which means we won't be able to fix this here unless Google publishes changes to their own metadata first.

Numberjack is likely out of date and not accurately reflecting the most recent data.

**Comment by pranavkedia** [comment]
There is a bug. e.g.
```
irb(main):070:0> TelephoneNumber.parse('+491788').valid?
=> true
```

`+491788` is clearly an invalid number, but this gem treats it as valid.

**Comment by pranavkedia** [comment]
As suggested in https://github.com/mobi/telephone_number/issues/99, we are using https://github.com/daddyz/phonelib for validation. It works on the same Google metadata. We and the result of both this gem and phonelib gem.
