### ISSUE TITLE
Gem does not support the numbers from Sri Lanka and Vietnam

### ISSUE THREAD

**Issue by AndreiBujenitsa** [mobi/telephone_number#111]
Could you add please the numbers from Sri Lanka and Vietnam? Because at the moment it seems to not work.

Example:
`pry(main)> TelephoneNumber.parse("+84283456789").valid?
=> false
`
`
pry(main)> TelephoneNumber.parse("+84283456789").country.country_id
NoMethodError: undefined method 'country_id' for nil:NilClass`

**Comment by espen** [comment]
This phone number is parsed but not defined as valid according to libphonenumber: https://giggsey.com/libphonenumber/index.php?phonenumber=%2B84283456789&country=&language=&region=
