### ISSUE TITLE
Version 1.4.17 seems to have disappeared

### ISSUE THREAD

**Issue by barisbalic** [mobi/telephone_number#120]
Our lockfile includes 1.4.17, but today I was no longer able to bundle.  Took a look at Rubygems and saw the jump from .16 to .18, so also checked the CHANGELOG and see the same thing.  Did something happen?  Any information would be appreciated, mostly so we know if there's something to worry about.

**Comment by jaykravetz** [comment]
I know this is waaaay late but there was an issue with 17 and we pulled it. I hope it didn't cause too much stress - I apologize for the inconvenience.

Everything should be good going forward.
