### ISSUE TITLE
Namespace - TelephoneNumber is too common

### ISSUE THREAD

**Issue by jakcharlton** [mobi/telephone_number#39]
I would love to use this gem as it seems to solve issue both Phony and GlobalPhone have, but ...

We already have a class named TelephoneNumber in our application, that coincidentally is a telephone number

Using the constant TelephoneNumber, without any namespacing, is likely to not only clash with our application, but with others too

On a more philosophical level, you are using a constant that is a noun as opposed to a name that represents a library for number parsing/formatting

Any chance this can be namespaced without us having to fork and namespace it ourselves? (which will make updates impossibly hard)

**Comment by jakcharlton** [comment]
Having needed to make progress on our business problem, I have taken the liberty of forking and renaming the project, also taking the liberty of appropriating your demo app name, as it was an ideal gem name https://github.com/leadmachineapp/numberjack

If you have a problem with the name I will be happy it rename it to something else

**Comment by akfernun** [comment]
Hi @jakcharlton, 

Thank you for submitting this. Would it be possible for you to rename the gem to something else?
We're open to changing the name, but will need some time to do so.  When we do make the switch, we would like to change it to numberjack.

**Comment by jakcharlton** [comment]
Well if you are happy to rename, and want to use the name Numberjack, perhaps you could just take over the repo I have forked? No code changes have been made, other than a full rename

You could then End Of Life the current repo and switch development to the renamed one?

**Comment by akfernun** [comment]
Hi @jakcharlton, 

While this is something that we're open to, it's something that will take some time on our part because of some of the dependencies on it. At this point in time, we would really like to own the "numberjack" gem name since we already own the domain. Would you mind transferring ownership of the gem to us and re-publishing under a different name? Afterwards, we can start working on transferring development over to that.

**Comment by jakcharlton** [comment]
The repo has been deleted, the gem has been yanked - you can pick it back
up when you get a renamed version

Good luck with it

**Comment by akfernun** [comment]
Thank you @jakcharlton. 

Good luck with your version as well.
