### ISSUE TITLE
Validates telephone number against all or multiple countries 

### ISSUE THREAD

**Issue by dinatih** [mobi/telephone_number#56]
Is it possible to validate active model without specify a country ? 
ex: 
```ruby
validates :phone_number, presence: true, telephone_number: true
``` 
Thank you

**Comment by akfernun** [comment]
Hey @dinatih, 

Unfortunately this is not possible in today's implementation. In general we can't validate a number for every single country for a couple of reasons. 

1. Performance. Doing this could be costly. 
2. Ambiguity in Numbers. Without knowing anything about a number, it can be really difficult to determine what to even look for in the number ie(prefix like '+1', etc)

If you're looking to validate against multiple countries, I would recommend writing a custom validator and doing something like below. 

```   
 if [country_codes....].none?{ |code| TelephoneNumber.valid?(value, code) }
      record.errors.add(attribute, :invalid)
 end
```

**Comment by dinatih** [comment]
Hello @akfernun, thank you I will do that it is perfect.
