### ISSUE TITLE
3739030345 numer is not valid even libphonenumber-js  allowed it

### ISSUE THREAD

**Issue by waleedarshad** [mobi/telephone_number#60]
libphonenumber-js allow this number to be valid in Pakistan but telephone_number does not allow it. is telephone_number is not using method provided by libphonenumber-js?

**Comment by akfernun** [comment]
Hey @waleedarshad, 

Thanks for bringing this up. Can your provide the phone number you're talking about?

**Comment by akfernun** [comment]
Hey @waleedarshad, 

I dug into this a little bit. This library is based on Google's [original libphonenumber library](https://github.com/googlei18n/libphonenumber). According to their data, the phone number you provided is not actually valid. [This link](https://libphonenumber.appspot.com/phonenumberparser?number=923739030345&country=PK) is from their official demo and shows why it isn't valid. This library is strictly based on Google's, so we do our best to ensure that our results are in line with theirs. Feel free to let us know if you find any other issues.

**Comment by waleedarshad** [comment]
HI @akfernun 

I have attached screenshot and this is from official demo. you have not added + in the country code that is why it is saying invalid

![libphonenumber js](https://user-images.githubusercontent.com/5329697/45941755-0d8e6d80-bff9-11e8-9655-5103944c05b9.png)

**Comment by waleedarshad** [comment]
@akfernun i have not heard from you. would you like to guide me if i am doing something wrong?. Need you help as i am using this library in mobile and pure libphonenumber-js  in ionic 3. you help would be much appreciated

Thanks

**Comment by akfernun** [comment]
Hi @waleedarshad, 

Please keep in mind that this is an open source library. What that means is that all maintenance and bug fixes are done in my spare time. This also means that I may not have responses as fast as you would like. However, the beauty in open source is that you can actually view all of the code, which means if you think there is a bug, you could research it and find a fix. Have you taken steps to troubleshoot this yourself?

Regardless, as mentioned above, you're not using a Google-supported library. You stated that you're using [this library](https://github.com/catamphetamine/libphonenumber-js). This is not supported by Google, which means there is a possibility that it is giving you incorrect results in this case. As stated above, I've researched this number and according to Google's official library (which can be found [here)](https://github.com/googlei18n/libphonenumber), the number you provided me with is invalid. The official library demo can be found at https://libphonenumber.appspot.com/. 

One alternative that you do have is to continue using this gem and define an override file that will whitelist the number in question. The instructions for doing that can be found on the readme. 

Unfortunately, there's not any more help that I can provide to you.

**Comment by waleedarshad** [comment]
Hi @akdarrah 

Thanks and sorry for taking much time of you. yes i did not try to debug. my bad!. Also it was not in my mind that libphonenumber-js library is not officially supported, again my mistake. that is why i was assuming it would definitely be the mistake in this library.

But your feedback has given me new direction that i should debug myself before asking question as it can solve most of my problem. Also can save lot of time of others.

Thanks Adam, you are a true guider.
