### ISSUE TITLE
'+35725963888' is not parsed as a valid number

### ISSUE THREAD

**Issue by papadeltasierra** [mobi/telephone_number#68]
Ref: https://www.itu.int/oth/T0202000034/en
I believe this phone number is valid but this Gem claims not.
This Python port, https://github.com/daviddrysdale/python-phonenumbers, parses the number as valid as does the on-line Java implementation at http://libphonenumber.appspot.com/
Note that this is not the only number that other implementations accept but this Gem does not.

**Comment by trouta23** [comment]
Hey there @papadeltasierra, my testing shows that this number is valid:

<img width="558" alt="3__ruby" src="https://user-images.githubusercontent.com/13686303/52903269-d491a800-31e8-11e9-9823-c42d9c1d54f1.png">

Can you confirm that you're on an up to date version or passing the information correctly, and then test the others that don't work?

Thanks!

**Comment by papadeltasierra** [comment]
If you `parse("+35725963888")` (you need the '+' for an E.164 number) then the Gem declares the number is 'valid' but if you enter a country too so `parse("+35725963888", :uk)` then your Gem claims this is an invalid number.
Both the Python port and Google's on-line example allow the country to be specified and still parse the number as valid.  I'll cut-n-paste some Irb output below...
`irb(main):013:0> phone_object = TelephoneNumber.parse("+35725963888", :uk)                                                                                                      
=> #<TelephoneNumber::Number:0x005628c4844660 @original_number="35725963888", @country=nil, @parser=#<TelephoneNumber::Parser:0x005628c4844480 @original_number="35725963888", @country=nil, @valid_types=[]>, @formatter=#<TelephoneNumber::Formatter:0x005628c4844458 @normalized_number=nil, @country=nil, @valid=false, @original_number="35725963888">>
irb(main):014:0> phone_object.valid?
=> false`

**Comment by papadeltasierra** [comment]
Forgot to add, yes, this is the up to date version (it matches the latest 'tag' on GitHub repo).

**Comment by trouta23** [comment]
Hey there @papadeltasierra, 

For `TelephoneNumber`, the scenario that you're running into is when you pass a country to the `parse` method and then checking for validity, you're asking if that number is valid for the country you passed it. When looking at Google's library, the functionality that we are recreating is `isValidNumberForRegion`. 

<img width="429" alt="https___libphonenumber_appspot_com_phonenumberparser_number__2b35725963888_country_uk" src="https://user-images.githubusercontent.com/13686303/52961740-a38cb100-3369-11e9-96da-99dfc79054d4.png">

The above image shows your example number using Google's official demo, the only library we care about, and you can see that the number is not valid for the country you're wanting to pass. It is a valid number somewhere, but not for the UK (valid for Cyprus). 

We do not have current plans to change the functionality to base our validity on `isValidNumber()` or `isPossibleNumber()` or break them apart, meaning if you pass a country then we are going to validate against the country.

I do not know your use case, but here are my suggestions:
- Do not pass a country and let the gem parse it for you
  - The example number you provided is valid, just not for the region you passed. Google also confirms this. 
- Create an override file and change the validations if you need that number to be valid for the given region
  - You run the risk of allowing unintended, invalid numbers to now be valid
- Change how you are building associations with your data

Hopefully that clears up any confusion on why you are getting the results that you are.

Thanks!

**Comment by papadeltasierra** [comment]
Austin, I have to disagree and here's why.
1. The use case is a website where users can enter telephone numbers.  Most users will enter the number in their national format; for example if I am in the UK and want to store a US number, I might type '00 1 123 456 7890'.  But a smarter user, especially one used to mobile phones, might enter '+1 123 456 7890'.  Your Gem seems to require me to validate these numbers, logically the same number, using two different validation schemes - is that even possible in ActiveRecord? (Or write my own validator).
2. As per the example in #1, I can dial a '+/E.164' number from anywhere in the world on my mobile and the mobile phone network will sort things out so an E.164 number is implicitly valid in any country (of course not for a landline!).
3. Whilst you are quite right that the Cypriot number is not valid as a UK number, libphonenumbers has identified it as a valid number because '+357' identifies it as Cypriot and so it can be validated.  You can prove this is happening by stripping the last '8' which means libphonenumbers still identifies it as Cypriot but then also spots that the number is not a valid Cypriot number - so country specific validation is happening, and for the correct country.
4. Finally whilst I can't dial this number from the UK (and the ITU document implies I could not dial this number without some prefixing even in Cyprus), for other port of Google Libphonenumbers I can validate the number and then convert to either format (local or E.164) to E.164 for storage and then render them to users in their correct local format.
I hope this explain my use case and why I believe this Gem, appearing different from other ports, makes validating user entered phone numbers difficult.
However it sounds like if you still disagree then I can work around this by implementing my own validator which will use the isValidNumber() result in the manner than I required.
