### ISSUE TITLE
I get inconsistent result with appphonelib

### ISSUE THREAD

**Issue by pangtongs** [mobi/telephone_number#85]
Using this gem, I will get that a number is a mobile
![image](https://user-images.githubusercontent.com/6629520/89749094-97158e80-daf0-11ea-8228-9b58b7224a6c.png)

Whereas if I take from the source (https://libphonenumber.appspot.com/phonenumberparser?number=62818731241&country=ID)
will be a fixed line result (fixed line result should be the correct one)
![image](https://user-images.githubusercontent.com/6629520/89749109-a09ef680-daf0-11ea-89ff-fd2bf09d46e6.png)

**Comment by joshwetzel** [comment]
Hi @pangtongs,

The national number, 818731241, does not match the fixed line regex pattern [provided upstream by Google](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L12438-L12511). It does match the [mobile number pattern](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L12512-L12516) though. I am not sure why there is a discrepancy between their demo and their published metadata.

Unfortunately we must rely on the metadata they provide for our official releases, which means we won't be able to fix this here unless Google publishes changes to their own metadata first. I would recommend [submitting an issue with Google](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue) and [overriding the fixed line validations](https://github.com/mobi/telephone_number#override-file) until it can be fixed upstream and we cut a new release.

**Comment by joshwetzel** [comment]
@pangtongs, my mistake, I removed the country code 62 from 818731241 when I was testing. I do see their metadata considers 62818731241 to be a valid fixed line so I will take another look at this. Sorry for the confusion!

**Comment by pangtongs** [comment]
thanksss for the reply
