### ISSUE TITLE
CHANGELOG.md file missing

### ISSUE THREAD

**Issue by danielgomezrico** [mobi/telephone_number#91]
Hi

I find that the releases tag shows which versions exists but I can't find a place to show what changed when, so I can know why I should update or not.

Having a file `CHANGELOG.md` is a good way or putting the changes on relases/ on github is another one.

What do you think?

**Comment by joshwetzel** [comment]
I agree. Most of the releases are simply metadata updates, but we'll include a change log in some way moving forward.
