### ISSUE TITLE
Phone numbers in Ivory Cost will change format by the end of January 2021

### ISSUE THREAD

**Issue by hkairi** [mobi/telephone_number#92]
The validation of phone numbers won't work for the new format in Ivory Cost. Phone numbers will move from 8 to 10 digits.

**Comment by hkairi** [comment]
[PR93](https://github.com/mobi/telephone_number/pull/93) solves this issue

**Comment by joshwetzel** [comment]
Changes included with https://github.com/mobi/telephone_number/pull/95.
