### ISSUE TITLE
How to run and csv upload

### ISSUE THREAD

**Issue by hummans** [mobi/telephone_number#94]
Hello i m new at this and ruby , please can you explain how to run? after gem install telephone_number what should i do to run? 
And how can i make csv upload and get generated csv ? Thnx

**Comment by joshwetzel** [comment]
Hi @hummans - please take a look at our [README](https://github.com/mobi/telephone_number/blob/master/README.md) for usage instructions. We are happy to answer any questions specific to this gem, but unfortunately are not able to provide support for individual integrations.

**Comment by hummans** [comment]
Thnx for your reply
the question is simple , how to run?
i have installed as root on ubuntu 20.04 server with command: gem install telephone_number
but i have not found a way of how to run it, i google it for gems & ruby but no answer anywhere
only this but not clear: https://stackoverflow.com/questions/9792803/how-do-i-run-a-ruby-gem
This is funny 
THNX

**Comment by hummans** [comment]
The README is for after you have run it, only the usage
but how do i get there

**Comment by hummans** [comment]
Just give me the first command to type after install
THNX

**Comment by joshwetzel** [comment]
There's no built-in CLI, but you could probably do something like this:

```ruby
#!/usr/bin/env ruby
require 'telephone_number'
TelephoneNumber.valid?('n')
```

Then execute with `ruby path/to/file.rb`.

**Comment by hummans** [comment]
thnx a lot
that was
